namespace BasicDisplayConfiguration
{
    [default_interface]
    runtimeclass Toolbox : MicrosoftDisplayCaptureTools.ConfigurationTools.IConfigurationToolbox
    {
        Toolbox(MicrosoftDisplayCaptureTools.Framework.ILogger logger);
    }

    [default_interface] runtimeclass ToolboxFactory : MicrosoftDisplayCaptureTools.ConfigurationTools.IConfigurationToolboxFactory
    {
        ToolboxFactory();
    }
}
