namespace BasicDisplayConfiguration
{
    [default_interface] runtimeclass Toolbox : MicrosoftDisplayCaptureTools.ConfigurationTools.IConfigurationToolbox
    {
        Toolbox();
    }

    [default_interface] runtimeclass ToolboxFactory : MicrosoftDisplayCaptureTools.ConfigurationTools.IConfigurationToolboxFactory
    {
        ToolboxFactory();
    }
}
