namespace SamplePlugin
{
    struct CaptureCapabilities
    {
        Boolean getImage;
        Single tolerance; // percentage error allowed - set 0 for raw capture.
    };

    enum PixelFormat
    {
        RGB8 = 0,
        YCbCr8 = 1,
        RGB16 = 2,
        YCbCr16 = 3
    };

    struct FrameCharacteristics
    {
        UInt32 height;
        UInt32 width;
        PixelFormat format;
        UInt32 bytes;
    };

    runtimeclass GraphicsCapturePlugin
    {
        GraphicsCapturePlugin();
        GraphicsCaptureDeviceInput InitializeCaptureInput(UInt32 displayId);

        UInt32 GetCaptureInputCount();
        void GetCaptureInputDisplayIds(ref UInt32[] captureInputUniqueId);
    }

    runtimeclass GraphicsCaptureDeviceInput
    {
        GraphicsCaptureDeviceInput(UInt32 captureInputUniqueId, GraphicsCapturePlugin plugin);

        CaptureCapabilities GetCaptureCaps();
        GraphicsCapturedFrame CaptureFrame();

        UInt32 UniqueId { get; };
    }

    runtimeclass GraphicsCapturedFrame
    {
        GraphicsCapturedFrame(FrameCharacteristics frameCharacteristics);
        FrameCharacteristics GetFrameCharacteristics();
        void GetFramePixels(ref UInt8[] buffer);
    }
}
