namespace DisplayControl
{
    [default_interface]
    runtimeclass DisplayEngine : MicrosoftDisplayCaptureTools.Display.IDisplayEngine
    {
        DisplayEngine(MicrosoftDisplayCaptureTools.Framework.ILogger logger);
    }

    [default_interface] 
    runtimeclass DisplayEngineFactory : MicrosoftDisplayCaptureTools.Display.IDisplayEngineFactory
    {
        DisplayEngineFactory();
    }
}
