namespace BasicDisplayControl
{
    [default_interface]
    runtimeclass DisplayEngine : MicrosoftDisplayCaptureTools.Display.IDisplayEngine
    {
        DisplayEngine();
    }

    [default_interface]
    runtimeclass DisplayEngineFactory : MicrosoftDisplayCaptureTools.Display.IDisplayEngineFactory
    {
        DisplayEngineFactory();
    }
}
