namespace TanagerPlugin
{
    [default_interface] runtimeclass Controller :
        MicrosoftDisplayCaptureTools.CaptureCard.IController,
        MicrosoftDisplayCaptureTools.CaptureCard.IControllerWithFirmware
    {
        // Default constructor, which is discovered by the framework
        Controller();
    }
}