namespace TestPlugin
{
    [default_interface]
    runtimeclass Controller : MicrosoftDisplayCaptureTools.CaptureCard.IController
    {
        // Default constructor, which is discovered by the framework
        Controller();
    }
}