namespace MicrosoftHardwareVerification
{
    //
    // The core of the Hardware HLK project, this object manages a running test, from parsing PICT parameters via TAEF to 
    // loading and coordinating with a display capture card's plugin.  
    //
    [default_interface]
    runtimeclass Framework
    {
        // Framework
        // ----------------------------------------------------------------------------------------------------------------
        // Notes:
        //      Constructs a Framework object with a specified capture card.
        //
        // Parameters:
        //      pluginPath
        //          This string represents a filepath from which a conformant capture card plugin implementation is exposed.
        //
        Framework(String pluginPath);

        // OpenToolbox
        // ----------------------------------------------------------------------------------------------------------------
        // Notes:
        //      Adds a Toolbox to the Framework, any configuration tools exposed by the Toolbox opened here will now be 
        //      available to the Framework for test runs.
        //
        // Parameters:
        //      toolboxPath
        //          This string represents a filepath from which a conformant Toolbox implementation is exposed.
        //
        void OpenToolbox(String toolboxPath);

        // RunPictTest
        // ----------------------------------------------------------------------------------------------------------------
        // Notes:
        //      This method will begin running tests based on PICT metadata received through TAEF, along with whichever
        //      Toolboxes have been provided to the framework.
        //
        void RunPictTest();
    }
}